apiVersion: v1
kind: Service
metadata:
  name: passwordless-app
  namespace: passwordless-auth
spec:
  type: ClusterIP
  ports:
    - port: 10000
      targetPort: 10000
  selector:
    app: passwordless-app
