# k8s/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: passwordless-app-hpa
  namespace: passwordless-auth
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: passwordless-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70   # Scale when CPU usage >70%
