apiVersion: v1
kind: PersistentVolume 
metadata:
  name: mongo-pv 
  namespace: passwordless-auth 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongo